name: Build Laravel Project

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: main
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: admin
          MYSQL_DATABASE: laravel_test_db
          MYSQL_USER: laravel_user
          MYSQL_PASSWORD: secrete
        ports:
         - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
          
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node js Environment Setup
        uses: actions/setup-node@v4
        with:
          node-version: '22'
        
      - name: Install NPM & Build
        run: |
         npm ci
         npm run build

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
         php-version: '8.3'
         extensions: mbstring, xml, mysql, pdo, pdo_mysql, bcmath, ctype, fileinfo, json, tokenizer, openssl
         tools: composer:v2

      - name: Copy .ENV
        run: |
          cp .env.testing .env

      - name: Setup Environment Variable
        run: |
          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_DATABASE=laravel_test_db" >> .env
          echo "DB_USERNAME=laravel_user" >> .env
          echo "DB_PASSWORD=secrete" >> .env

          echo "DB_CONNECTION=mysql" >> .env.testing
          echo "DB_HOST=127.0.0.1" >> .env.testing
          echo "DB_PORT=3306" >> .env.testing
          echo "DB_DATABASE=laravel_test_db" >> .env.testing
          echo "DB_USERNAME=laravel_user" >> .env.testing
          echo "DB_PASSWORD=secrete" >> .env.testing


      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-interaction --no-scripts

      - name: Wait for MySQL
        run: sleep 15

      - name: Key Genarate and Migrate
        run: |
          php artisan key:generate
          php artisan migrate --env=testing

      - name: Execute Category Test
        run: php artisan test --env=testing

      # - name: Prepare Artifact Folder
      #   run: |
      #     mkdir -p artifact
      #     cp -r app bootstrap config database public resources routes storage artisan composer.* .env.testing .env artifact/
      #     cp -r vendor node_modules artifact/ # optional if needed in artifact

      - name: Push Code
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST_NAME }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.HOST_SSHKEY }}
          source: "./*"
          target: "/var/www/html/learnwithmehrab.com/public_html/"
          
          
         


      # - name: Upload Laravel Artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: laravel-app-artifact
      #     path: artifact


  # deploy:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Download Artificat
